### ISSUE TITLE
MetaballMenuClickListener

### ISSUE THREAD

**Issue by athirasanthosh** [melvinjlobo/Collapsible-Toolbar-Helper#1]
I need to implement MetaballMenuClickListener. How can i implement this.

 metaball_menu.setMenuClickListener(new MetaballMenu.MetaballMenuClickListener() {
            @Override
            public void onClick(View view) {

```
        }
    });
```

I have added this into main activity. but how can i get menu button id.

**Comment by melvinjlobo** [comment]
You can get the ID by using view.getId()
